services:
  - type: web
    name: nextjs-static
    runtime: static
    buildCommand: yarn; yarn build
    staticPublishPath: out
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production

